# specify the language runtime
runtime: nodejs

# specify whether flexible environment should be used (auto-scaling)
env: flex

# specify env variables
env_variables:
  # I can access this variable on the gcloud
  AGE: "20"
  
  # I didn't bother trying to test this out since apps on app engine read from the .env file directly
  # env_file:
  # - some_file.env